name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_DATABASE: laminas_test
            MYSQL_USER: laminas_test
            MYSQL_PASSWORD: laminas_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: pdo, mysql, zip
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-interaction --no-suggest

    - name: Checkout Laminas tests
      uses: actions/checkout@v2
      with:
        repository: Naktibalda/codeception-laminas-tests
        path: framework-tests
        ref: 'master'
        submodules: recursive

    - name: Install dependencies of Laminas tests
      run: |
        composer update --no-dev --prefer-dist --no-interaction
        php vendor/bin/doctrine-module orm:schema-tool:create
      working-directory: framework-tests

    - name: Run test suite
      run: |
        php vendor/bin/codecept build -c framework-tests
        php vendor/bin/codecept run functional -c framework-tests
