name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_DATABASE: laminas_test
            MYSQL_USER: laminas_test
            MYSQL_PASSWORD: laminas_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        php: [8.0]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: pdo, mysql, zip
        coverage: none

    - name: Downgrade to composer v1
      run: composer self-update --1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Checkout Laminas tests
      uses: actions/checkout@v2
      with:
        repository: Naktibalda/codeception-laminas-tests
        path: framework-tests
        ref: '5.0'
        submodules: recursive

    - name: Install dependencies of Laminas tests
      run: composer update --no-dev --prefer-dist --no-interaction
      working-directory: framework-tests

    - name: Create database schema
      run: php vendor/bin/doctrine-module orm:schema-tool:create
      working-directory: framework-tests

    - name: Run test suite
      run: |
        php vendor/bin/codecept build -c framework-tests
        php vendor/bin/codecept run functional -c framework-tests
